In [1]:
import numpy as np
import tensorflow as tf

In [3]:
a = np.array([
    [2.1, 3.1, 3.9],
    [3.2, 4.5, 3.1]
])

In [5]:
print(a)
print(a.shape)

[[2.1 3.1 3.9]
 [3.2 4.5 3.1]]
(2, 3)


In [11]:
np.mean(a, axis=0)

array([2.65, 3.8 , 3.5 ])

In [12]:
a + 3

array([[5.1, 6.1, 6.9],
       [6.2, 7.5, 6.1]])

In [35]:
with tf.name_scope('abc'):
    a = tf.constant(3, dtype = tf.float32, name = 'const')
print(a)

Tensor("abc_1/const:0", shape=(), dtype=float32)


In [40]:
with tf.Session() as sess:
    print(sess.run(a))

3.0


In [73]:
a = tf.constant(3, dtype = tf.float32, name = 'const')
b = tf.Variable(0, dtype = tf.float32)
c = tf.assign(b, a + b) # b 에다가 a + b 할당
print(a)
print(b)

init = tf.global_variables_initializer()

Tensor("const_18:0", shape=(), dtype=float32)
<tf.Variable 'Variable_8:0' shape=() dtype=float32_ref>


Session 내부에서는 그래프를 그리지 않는다 ( + 연산도 graph를 그리는 작업이다. )

In [74]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(c))
    print(sess.run(c))

3.0
6.0


In [97]:
np.random.seed(42)
x = tf.placeholder(tf.float32, shape = (), name = 'x')
y = tf.placeholder(tf.float32, shape = (), name = 'y')
w = tf.Variable(np.random.randn(), dtype = tf.float32 )

a = tf.assign(w , w + x + y)


init = tf.global_variables_initializer()

In [98]:
with tf.Session() as sess:
    sess.run(init)
    for i in range(0, 10):
        print(sess.run(w))
        sess.run(a, feed_dict = {x:i, y : i})
    print(sess.run(w))

0.49671414
0.49671414
2.496714
6.496714
12.496714
20.496714
30.496714
42.49671
56.49671
72.49671
90.49671
